### ISSUE TITLE
Expo+snow doesn't look good (using four viewports)

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-experimental#14]
Window manager: Expo+snow doesn't look good (using four viewports, and probably other numbers also): When entering expo, the snow gets zoomed out, and split into four segments corresponding to the four desktops — but it *overflows* the area of the desktops. This looks very weird.

**Comment by soreau** [comment]
Can you post a screenshot? It looks ok to me

**Comment by ethus3h** [comment]
![screenshot_2016 09 16_07 39 54](https://cloud.githubusercontent.com/assets/10457522/18584746/d1be9b94-7be0-11e6-910e-c326326259c0.png)

There are a couple solutions that would make sense IMO (from an aesthetic perspective; IDK about technically): a) clip the snow to the viewports, or b) not have the snow separated by the Expo viewport distance.

**Comment by soreau** [comment]
It took awhile for me to get anything close to this 'problem', I had to make expo viewports farther apart and snowflakes bigger at least, and even then I did not find the rendering to be unacceptable, that's what it's supposed to do. Closing this as NOTABUG.
