### ISSUE TITLE
Screensaver and Freewins Plugins Problem!

### ISSUE THREAD

**Issue by cokomokoo** [compiz-reloaded/compiz-plugins-experimental#19]
Screensaver and Freewins Plugins not work?

**Comment by soreau** [comment]
Freewins has known issues that may cause unresponsive desktop. Screensaver should work fine.

**Comment by cokomokoo** [comment]
Freewins running the only hotkey.
Screensaver never work.

**Comment by cokomokoo** [comment]
Now, I recompile and Screensaver plugin work fine.
There are also some stability problems Freewins plugin.
Thanks.
