### ISSUE TITLE
Cannot Compile Cloned Repo With Autoconf

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [compiz-reloaded/compiz-plugins-experimental#2]
Am I missing something here? Tried compiling the source using autoconf in ubuntu 16.04 and get the following error:

aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:18: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:19: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
autoconf: configure.ac: AM_GNU_GETTEXT_VERSION is used, but not AM_GNU_GETTEXT
configure.ac:18: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:19: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
autoconf: /usr/bin/autoconf failed with exit status: 1

**Comment by XRevan86** [comment]
You don't have gettext installed.

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for reference, added the following tools:

sudo sudo apt-get update && sudo apt-get install autotools-dev libltdl-dev libtool autoconf autopoint

ran autoreconf -fiv which seems to have worked - Cant get much further than that though

**Comment by XRevan86** [comment]
Use ```./autogen.sh``` or ```NOCONFIGURE=1 ./autogen.sh``` (that is with and without instantly running ./configure).

**Comment by danieledwardgeorgehitchcock** [comment]
No package 'compiz' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables COMPIZ_CFLAGS
and COMPIZ_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

I have compiz installed - distro (if it makes a difference is Ubuntu MATE)
