### ISSUE TITLE
Plugin:compiz-earth

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#26]
add new plugin

https://github.com/matijaskala/compiz-earth/tree/eb5194ac6ee434a0153af22aec2cf94572c8df77

**Comment by soreau** [comment]
Nice plugin, would be convenient to have a scaling option to size it and perhaps an icon for ccsm. We should import it to plugins-experimental, indeed.

**Comment by XRevan86** [comment]
Doesn't seem worth it: the plugin is a giant mess.
It can crash solely because ```~/.compiz/images/``` does not exist.

**Comment by ethus3h** [comment]
(My 2 cents is that if one's using plugins from -experimental, one probably expects that they wouldn't necessarily be ready for the prime time yet, so it doesn't really matter if they blow up at runtime as long as they compile...)

**Comment by Eignar17** [comment]
@soreau talk is creator plugin @matijaskala

**Comment by matijaskala** [comment]
Hello,
I added code for scaling and creating `~/.compiz/images`.
https://github.com/matijaskala/compiz-earth/tree/0.8
I hope it works correctly. I cannot test it with 0.9.

**Comment by Eignar17** [comment]
@matijaskala
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
compiling : earth.c -> build/earth.loearth.c: In function ‘earthInitScreen’:
earth.c:338:39: error: too few arguments to function ‘mkdir’
     if ((stat (imagedir, &st) < 0 && (mkdir (imagedir) < 0 || stat (imagedir, &
                                       ^
In file included from earth.h:12:0,
                 from earth.c:1:
/usr/include/x86_64-linux-gnu/sys/stat.h:320:12: note: declared here
 extern int mkdir (const char *__path, __mode_t __mode)
            ^
Makefile:284: fallo en las instrucciones para el objetivo 'build/earth.lo'
make: *** [build/earth.lo] Error 1

**Comment by soreau** [comment]
Thanks for your help @matijaskala and @Eignar17, earth is now upstream.

**Comment by Eignar17** [comment]
Thanks for your help @soreau  fix code

**Comment by soreau** [comment]
@matijaskala I forgot to add copyright headers to source files but will do it soon enough.

**Comment by Eignar17** [comment]
is rare new bug in to new compiz 0.8.14 update is new code create is bug
![screenshot at 2017-04-18 22 53 23](https://cloud.githubusercontent.com/assets/8561550/25162639/fc6e2484-2489-11e7-9080-6e3d8281d989.png)

**Comment by ethus3h** [comment]
I think bugs are to be expected when using plugins from -experimental...

**Comment by Eignar17** [comment]
@ethus3h  not is error not in compiz 0.8.12+ earth plugin my test in to plugin is stable is new update is bug :/

**Comment by ethus3h** [comment]
Oh, interesting. Could you describe what's unexpected about it? The screenshot looks normal enough, but since I don't use Cube or Earth I don't really know what's wrong in it for sure...

You might try building with one or more of the patches that aren't in the known-good Earth plugin reverted... maybe that would help isolate a single change that introduces the problem?
