### ISSUE TITLE
Multi-touch Compiz Plugin

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#27]
add plugin of list in compiz-reloaded
info:
https://jamcnaughton.com/2010/05/20/how-to-install-the-compiz-multi-touch-plugin/

view plugin:
https://www.youtube.com/watch?v=rY-85BUqWgY

@soreau

**Comment by ethus3h** [comment]
Did you close this intentionally?

**Comment by Eignar17** [comment]
@ethus3h is code I'm not sure is to plugin Useful

**Comment by ethus3h** [comment]
It looks cool in the video, heh. One thing I would like to see (eventually — probably not anytime soon) is Windows 10-style touch event visualization. I'll probably open a feature request for that at some point...

**Comment by Eignar17** [comment]
@ethus3h work in to plugin?

**Comment by Eignar17** [comment]
@ethus3h is plugin Requires liblo-dev is code Many bugs
(https://github.com/compiz-reloaded/compiz-plugins-experimental/files/981229/error.multi-touch.txt)
work in code is much Still want add in to compiz-reloaded?

**Comment by ethus3h** [comment]
@Eignar17 why are you pinging me, is there something you're trying to ask? Your comments don't make sense to me

**Comment by Eignar17** [comment]
ok not add plugin in to compiz

**Comment by Eignar17** [comment]
error in compile is lines for bug simple
