### ISSUE TITLE
Plugin:newton

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#28]
new plugin
http://forum.compiz.org/viewtopic.php?f=89&t=8555&hilit=xytovl&start=20

last update

[newton.zip](https://github.com/compiz-reloaded/compiz-plugins-experimental/files/926576/newton.zip)

https://ubuntuforums.org/showthread.php?t=1414467&page=3

and icon
https://github.com/smspillaz/compiz-fusion-icons/blob/master/oxygen/plugin-newton.svg

**Comment by Eignar17** [comment]
@ethus3h add plugin to compiz-plugins-community

**Comment by ethus3h** [comment]
Fixed as of https://github.com/ethus3h/compiz-plugins-community/commit/447c3877b9433f9bb40d935f80fa68e11feb5aaf
