### ISSUE TITLE
Plugin: Amiga Boing and Roaches

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#29]
new plugin
http://forum.compiz.org/viewtopic.php?f=89&t=8668&hilit=Roach
http://forum.compiz.org/viewtopic.php?f=89&t=8662&p=60183&hilit=boing#p60183

**Comment by Eignar17** [comment]
@ethus3h help update plugin for compiz-reloaded

**Comment by ethus3h** [comment]
Sorry @Eignar17, I don't really have enough time and energy to do much work on the plugins I won't be using personally :(

**Comment by Eignar17** [comment]
update 
compiz-boing
https://github.com/matijaskala/compiz-boing
compiz-roach
https://github.com/matijaskala/compiz-roach
@soreau 
icons for plugins
https://github.com/Eignar17/compiz-fusion-icons

**Comment by ethus3h** [comment]
For what it's worth, I've created a new package for community plugins that aren't officially included in Compiz, with the roach plugin to start it off: https://github.com/ethus3h/compiz-plugins-community
