### ISSUE TITLE
Ghost plugin

### ISSUE THREAD

**Issue by wolfen351** [compiz-reloaded/compiz-plugins-experimental#3]
Hi there

I would love to use your ghost plugin to make VLC transparent, but i'm unable to get the code to compile on ubuntu 14.04. Can you help with any pointers?

Thanks

**Comment by raveit65** [comment]
compiz-0.9.x isn't compatible to compiz-reloaded.
You need to uninstall 0.9.x version and compile the complete compiz-reloaded stack by hand.

**Comment by soreau** [comment]
You can read blog.northfield.ws or join #compiz-reloaded on irc.freenode.net where we can better assist you.
