### ISSUE TITLE
compiz-cube-rubik

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#30]
new plugin
http://forum.compiz.org/viewtopic.php?f=89&t=6473&hilit=rubik

and icon
https://github.com/smspillaz/compiz-fusion-icons/blob/master/oxygen/plugin-rubik.svg

**Comment by Eignar17** [comment]
port to compiz 0.8
https://github.com/Eignar17/compiz-rubik

**Comment by Eignar17** [comment]
error windows on other side are not visible and drawing conflicts have mostly fixed is plugin not complete

**Comment by ethus3h** [comment]
As with #27, even if it doesn't work isn't it better to get the code integrated so that people who are interested in experimental plugins can help make them better?

**Comment by Eignar17** [comment]
in the post is complicated add plugin is not full vercion is all bugs is vercion in to compiz forum is create new and fix code is long time is reactivate for my ideas in to code or help in update code is funcion windows from rubik

**Comment by Eignar17** [comment]
is code in to #27  complicate is very hard code is update and not compile is code not fund sorry

**Comment by Eignar17** [comment]
@ethus3h talk is administrator to compiz 0.9 is code in to  [http://cgit.compiz.org/](url) lost all code T.T  code rubik and others plugins in beta not complete is pass to new project compiz-plugins-community

**Comment by Eignar17** [comment]
is code is update for full pass to plugin experimental work in to plugins :(

**Comment by ethus3h** [comment]
It's now in the new repository, using the code from https://github.com/Eignar17/compiz-rubik. It seems a little buggy; if you have changes feel free to open a PR. :)
