### ISSUE TITLE
Plugin:compiz-maze

### ISSUE THREAD

**Issue by Eignar17** [compiz-reloaded/compiz-plugins-experimental#32]
add new plugin
https://github.com/Eignar17/compiz-maze
http://forum.compiz.org/viewtopic.php?f=89&t=6567&hilit=Maze

icon for plugin
https://github.com/Eignar17/compiz-fusion-icons/blob/master/tango/plugin-maze.svg

**Comment by Eignar17** [comment]
@soreau  is my bug maze without going through the walls help me to fix erro?

**Comment by ethus3h** [comment]
(I saw this in my notifications and have added it to compiz-plugins-community.)
