### ISSUE TITLE
Ghost plugin error

### ISSUE THREAD

**Issue by SergioGeeK7** [compiz-reloaded/compiz-plugins-experimental#38]
Hi.
When I try to active Ghost plugin I receive this message on the terminal

`
compiz (ghost) - Error: InitObject failed
`
`compiz (core) - Error: Couldn't activate plugin 'ghost'`

Thank you in advance

**Comment by soreau** [comment]
Make sure you have [this commit](https://github.com/compiz-reloaded/compiz-plugins-experimental/commit/8c72fe03c77bd41bace875890a76178e7a2a8696).

**Comment by SergioGeeK7** [comment]
Hi soreau, I do but somehow when I active the plug-in it does not require "mousepoll" plugin, 
I activated it before ghost plugin and works now. THANK YOU. I was searching this feature for a long time.

**Comment by soreau** [comment]
It should prompt to enable mousepoll if it's not enabled when enabling ghost if you have this patch. It's possible you have other/old files installed to /usr/local/ or maybe ~/.compiz/. Closing for now.

**Comment by SergioGeeK7** [comment]
Hi soreau, I don't, this is my first time playing with this repo. I just download the master branch. run autogen.sh, config, make, make install

**Comment by soreau** [comment]
I'm not sure then, it works here ok.
