### ISSUE TITLE
Rofi not effected by add helper exclusion

### ISSUE THREAD

**Issue by psykotik1** [compiz-reloaded/compiz-plugins-experimental#39]
using this match set in add helper:

(Toolbar | Utility | Dialog | ModalDialog | Fullscreen | Normal) & !(title=rofi)

rofi still affected by add helper, tried using all specifications (name, class id, etc)

**Comment by soreau** [comment]
The main problem here is that compiz doesn't get any FocusIn or FocusOut events for the rofi window, so rofi never actually gains focus and becomes the active window. I am guessing this is a problem with the way rofi works as it doesn't behave like other windows in this regard.
