### ISSUE TITLE
Bug: addialog does not revive main window after closing dialog in doublecmd

### ISSUE THREAD

**Issue by sanderboom** [compiz-reloaded/compiz-plugins-experimental#4]
Addialog is an awesome plugin. Thanks.

When starting a copy action (f5) in Double Commander (http://doublecmd.sourceforge.net/) a dialog appears and addialog fades the main window. Killing the dialog (cancel, start, etc) will keep the main window 'dimmed'. 

XPROP for the copy-dialog:
```
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
```
The only diff between before and after state is the addition of:
```
_NET_WM_USER_TIME(CARDINAL) = 7140204
```

Hope this helps.

**Comment by ShadowKyogre** [comment]
Reproduced with GTK2 build of double commander. However, I wasn't able to reproduce this with the Qt4 build (<- instead, the main window isn't dimmed).

**Comment by ethus3h** [comment]
Oh, I think I duplicated this here: https://github.com/compiz-reloaded/compiz/issues/28

**Comment by ethus3h** [comment]
I can reproduce this reliably with LibreOffice 5.

**Comment by soreau** [comment]
@sanderboom Thanks for the detailed report.

I found out why it's happening, which turned out to be a core issue. [327f21d7](https://github.com/compiz-reloaded/compiz/commit/327f21d7dea785f025d0379c88d73438755fa098)  should fix it.

**Comment by ethus3h** [comment]
I've seen a similar issue where windows aren't getting revived correctly a few times, but not reliably like it was with LibreOffice...
