### ISSUE TITLE
Animations Plus Plugin: Bonanza Effect Duration 

### ISSUE THREAD

**Issue by Waerham** [compiz-reloaded/compiz-plugins-experimental#5]
Hello,

I like to use Random Effects, and after discussing it with soreau, since I set my Minimize Effect Duration to 600, for example, to have the Bonanza effect as part of a Random Effect setting is not tolerable because this specific animation takes at least 4 times longer to complete compared to the other animations. It's not possible to add Bonanza as it's own animation in addition to a Random Effects selection. I'm filing this report because I do like this effect, but it has to be set to a much lower duration to be usable. 

To quote soreau
"Basically the bonanza animation should be fixed to be The Right Duration, which is seemingly about 1/4 of what it is now. This is something that should be fixed in the 'hard coded' part of animations plus bonanza animation code."

Thanks for reading.

**Comment by ShadowKyogre** [comment]
@Waerham : Let me know if there's any issues with the fix I whipped up. Otherwise, closing for now.
