### ISSUE TITLE
Bug: Snow: When snowflake textures are large, they appear to have glitches/holes in them.

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-experimental#9]
I'm not sure what this is about, but it makes things look slightly unpolished.

**Comment by soreau** [comment]
Are you talking about the image file resolution or the size setting in ccsm? What steps reproduce the issue?

**Comment by ethus3h** [comment]
(Neither; there are some pixels missing in the default snowflake image. @ShadowKyogre made a patched version. It's included in the snowflakes PR I opened, FWIW.

**Comment by soreau** [comment]
I don't see a real problem here.

**Comment by ethus3h** [comment]
(When I get around to it, I'll post a patch file here with that fix only for anyone who wants to add it to their builds.)

**Comment by ethus3h** [comment]
Here's the patch: 

[snowflake-holes-patch-2016sept25n3.patch-zipped2016sept25a26.zip](https://github.com/compiz-reloaded/compiz-plugins-experimental/files/492214/snowflake-holes-patch-2016sept25n3.patch-zipped2016sept25a26.zip)

(Incidentally, I think this makes it a little smaller, in consideration of byte-shaving.)

**Comment by ethus3h** [comment]
Fixed by #15.
